// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IBM/sarama"
	"github.com/KATOmemorial/cronyx/internal/common"
	"github.com/KATOmemorial/cronyx/internal/config"
	"github.com/KATOmemorial/cronyx/internal/data"
	"github.com/KATOmemorial/cronyx/internal/discovery"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// initApp 初始化依赖
func initApp() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger := common.NewLogger(configConfig)
	dataData, cleanup, err := data.NewData(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	syncProducer, cleanup2, err := data.NewKafkaProducer(configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	election, err := discovery.NewElection(configConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(configConfig, logger, dataData, syncProducer, election)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App 调度器应用结构体
type App struct {
	conf     *config.Config
	logger   *zap.Logger
	data     *data.Data
	producer sarama.SyncProducer
	election *discovery.Election // 👈 新增依赖
}

// NewApp 构造函数
func NewApp(conf *config.Config, logger *zap.Logger, data2 *data.Data, producer sarama.SyncProducer, election *discovery.Election) *App {
	return &App{
		conf:     conf,
		logger:   logger,
		data:     data2,
		producer: producer,
		election: election,
	}
}
