// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/IBM/sarama"
	"github.com/KATOmemorial/cronyx/internal/biz"
	"github.com/KATOmemorial/cronyx/internal/common"
	"github.com/KATOmemorial/cronyx/internal/config"
	"github.com/KATOmemorial/cronyx/internal/data"
	"github.com/KATOmemorial/cronyx/internal/discovery"
	"github.com/KATOmemorial/cronyx/internal/server"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger := common.NewLogger(configConfig)
	consumerGroup, cleanup, err := data.NewKafkaConsumerGroup(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	serviceRegister := discovery.NewServiceRegister(configConfig, logger)
	executor := biz.NewExecutor(logger)
	workerGrpcServer := server.NewWorkerGrpcServer(executor, logger, configConfig)
	dataData, cleanup2, err := data.NewData(configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jobRepo := data.NewJobRepo(dataData, logger)
	app := NewApp(configConfig, logger, consumerGroup, serviceRegister, executor, workerGrpcServer, jobRepo)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App Worker 应用结构
type App struct {
	conf          *config.Config
	logger        *zap.Logger
	consumerGroup sarama.ConsumerGroup // 👈 这里改名并改类型了
	registrar     *discovery.ServiceRegister
	executor      *biz.Executor
	grpcServer    *server.WorkerGrpcServer
	repo          biz.JobRepo
}

func NewApp(
	conf *config.Config,
	logger *zap.Logger,
	consumerGroup sarama.ConsumerGroup,
	registrar *discovery.ServiceRegister,
	executor *biz.Executor,
	grpcServer *server.WorkerGrpcServer,
	repo biz.JobRepo,
) *App {
	return &App{
		conf:          conf,
		logger:        logger,
		consumerGroup: consumerGroup,
		registrar:     registrar,
		executor:      executor,
		grpcServer:    grpcServer,
		repo:          repo,
	}
}

// ProviderSet 定义 Discovery 相关的注入
// 因为 discovery 包还没把 NewServiceRegister 加入 ProviderSet，我们这里手动组装
var DiscoverySet = wire.NewSet(discovery.NewServiceRegister)
