// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/KATOmemorial/cronyx/internal/biz"
	"github.com/KATOmemorial/cronyx/internal/common"
	"github.com/KATOmemorial/cronyx/internal/config"
	"github.com/KATOmemorial/cronyx/internal/data"
	"github.com/KATOmemorial/cronyx/internal/server"
	"github.com/KATOmemorial/cronyx/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// initApp 初始化整个应用
// 返回 gin.Engine (用于启动 HTTP 服务) 和 cleanup 函数 (用于关闭 DB/Redis)
func initApp() (*gin.Engine, func(), error) {
	configConfig := config.NewConfig()
	logger := common.NewLogger(configConfig)
	dataData, cleanup, err := data.NewData(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	jobRepo := data.NewJobRepo(dataData, logger)
	jobUseCase := biz.NewJobUseCase(jobRepo, logger)
	jobService := service.NewJobService(jobUseCase)
	engine := server.NewHTTPServer(configConfig, jobService)
	return engine, func() {
		cleanup()
	}, nil
}
