// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/KATOmemorial/cronyx/internal/biz"
	"github.com/KATOmemorial/cronyx/internal/common"
	"github.com/KATOmemorial/cronyx/internal/config"
	"github.com/KATOmemorial/cronyx/internal/data"
	"github.com/KATOmemorial/cronyx/internal/discovery"
	"github.com/KATOmemorial/cronyx/internal/server"
	"github.com/KATOmemorial/cronyx/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// initApp 初始化应用，现在只返回一个 *App 主对象
func initApp() (*App, func(), error) {
	configConfig := config.NewConfig()
	logger := common.NewLogger(configConfig)
	dataData, cleanup, err := data.NewData(configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	jobRepo := data.NewJobRepo(dataData, logger)
	jobUseCase := biz.NewJobUseCase(jobRepo, logger)
	master := discovery.NewMaster(configConfig, logger)
	jobService := service.NewJobService(jobUseCase, master, logger)
	engine := server.NewHTTPServer(configConfig, jobService)
	app := NewApp(engine, master)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// App 定义一个结构体来包裹我们需要的所有组件
type App struct {
	Engine *gin.Engine
	Master *discovery.Master
}

// NewApp 构造函数
func NewApp(engine *gin.Engine, master *discovery.Master) *App {
	return &App{
		Engine: engine,
		Master: master,
	}
}
