// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求参数：只需要知道要杀哪个任务 (RunID)
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *StopRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应参数：告诉 API 成功没
type StopReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReply) Reset() {
	*x = StopReply{}
	mi := &file_api_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReply) ProtoMessage() {}

func (x *StopReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReply.ProtoReflect.Descriptor instead.
func (*StopReply) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *StopReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_worker_proto protoreflect.FileDescriptor

const file_api_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/worker.proto\x12\x05proto\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"?\n" +
	"\tStopReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2A\n" +
	"\rWorkerService\x120\n" +
	"\bStopTask\x12\x12.proto.StopRequest\x1a\x10.proto.StopReplyB*Z(github.com/KATOmemorial/cronyx/api/protob\x06proto3"

var (
	file_api_proto_worker_proto_rawDescOnce sync.Once
	file_api_proto_worker_proto_rawDescData []byte
)

func file_api_proto_worker_proto_rawDescGZIP() []byte {
	file_api_proto_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)))
	})
	return file_api_proto_worker_proto_rawDescData
}

var file_api_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_worker_proto_goTypes = []any{
	(*StopRequest)(nil), // 0: proto.StopRequest
	(*StopReply)(nil),   // 1: proto.StopReply
}
var file_api_proto_worker_proto_depIdxs = []int32{
	0, // 0: proto.WorkerService.StopTask:input_type -> proto.StopRequest
	1, // 1: proto.WorkerService.StopTask:output_type -> proto.StopReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_worker_proto_init() }
func file_api_proto_worker_proto_init() {
	if File_api_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_worker_proto_depIdxs,
		MessageInfos:      file_api_proto_worker_proto_msgTypes,
	}.Build()
	File_api_proto_worker_proto = out.File
	file_api_proto_worker_proto_goTypes = nil
	file_api_proto_worker_proto_depIdxs = nil
}
